### ISSUE TITLE
Input data's shape for sending to network

### ISSUE THREAD

**Issue by trung1309vn** [kamo-naoyuki/pytorch_convolutional_rnn#4]
Hi,

First I want to thank you for sharing such a great work. I am having some issue using the net, I hope you can manage sometime to explain it for me.

My input shape is like: (batch_size, number_of_features, image_rows, image_cols, image_sequence_length) - frame volume type.
I want to use the convolutional lstm layer for this. Which layer should I use and how can I translate my input into shape that the layer accept.

Thank you.

**Comment by kamo-naoyuki** [comment]
I update README.md just now. The explanation was really hard to understand, sorry.
You need to transpose the length axis to the first or second axis.

**Comment by trung1309vn** [comment]
Thank you for quick reply. I'll try it now.
